### ISSUE TITLE
Could not compile dependency erlang_v8

### ISSUE THREAD

**Issue by rogsmith** [le0pard/elixir_v8#1]
I am trying to run this within phoenix and I get the error: Could not compile dependency erlang_v8, ~/.mix/rebar command failed. If you want to recompile this dependency, please run: mix deps.compile erlang_v8. Any ideas?

**Comment by le0pard** [comment]
Without stack trace I cannot understand error.

**Comment by rogsmith** [comment]
mix deps.compile erlang_v8
==> erlang_v8 (compile)
make: **\* No rule to make target `v8'.  Stop.
ERROR: Command [compile] failed!

**Comment by le0pard** [comment]
```
$ mix deps.compile 
==> reloader (compile)
Compiled src/reloader.erl
==> erlang_v8 (compile)
mkdir -p lib
curl -L https://github.com/v8/v8/archive/49744859536225e7ac3b726e5b019dd99e127e6f.tar.gz | tar xvz -C lib
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   147    0   147    0     0    187      0 --:--:-- --:--:-- --:--:--   187
100   781    0   781    0     0    397      0 --:--:--  0:00:01 --:--:--   397x v8-49744859536225e7ac3b726e5b019dd99e127e6f/
```

Looks like all works. Project with phoenix: https://github.com/le0pard/js-api-service

**Comment by rogsmith** [comment]
so I am trying to use in phoenix and here is my mix file:

{:poolboy, "~> 1.4", optional: false, hex: :poolboy, override: true},
     {:elixir_v8, git: "https://github.com/le0pard/elixir_v8.git"}]

Perhaps there is some other dependency I need to setup?

**Comment by le0pard** [comment]
`elixir_v8` inside contain all deps

**Comment by rogsmith** [comment]
hrmm wonder what I am doing wrong then.

**Comment by le0pard** [comment]
You can try clone https://github.com/le0pard/js-api-service and make `mix deps.get && mix deps.compile` - if it also will fail - check `make`

**Comment by rogsmith** [comment]
yeah so it appears to have gotten futher for some unknown reason but when I try to compile js-api-service I get: ERROR: compile failed while processing /js-api-service/deps/edown: rebar_abort
==> js_api_service

**Comment by le0pard** [comment]
`edown` is not this package. Get vagrant box and try to compile in clear environment.

**Comment by rogsmith** [comment]
yeah agreed something wrong with my environment. in terms of this elixir_v8 package does it work on running javasxcript in same way node.js would run js ?

**Comment by le0pard** [comment]
Nope, in contain only v8 engine, it doesn't contain node.js packages ('path', 'http', etc)

**Comment by rogsmith** [comment]
ok but in terms of actually being able to intepret and run javascript code? it works well? I am trying to decide on building my project which I need to be able to run dynamic javascript in either phoenix or node.js

**Comment by le0pard** [comment]
yes, v8 - is javascript engine. Node.js build on top of it. More info: https://code.google.com/p/v8/

**Comment by le0pard** [comment]
I just updated `edown` on https://github.com/le0pard/js-api-service - it fail on my machine too.

**Comment by rogsmith** [comment]
ok trying again

**Comment by rogsmith** [comment]
ok looks like it compiled this time!. I will try to find out why not working in my app.

**Comment by le0pard** [comment]
ok, perfect.

**Comment by rogsmith** [comment]
I know you dont know my use case and I am new to elixir and phoenix, but do you think using this for my idea of running eval'd javascript code is a good one or better to just go with node?

**Comment by le0pard** [comment]
I used this for my project to `eval` user js code safety (because if user will create infinite loop - supervisor have timeout for actors). For node.js you need create sandbox env - because node.js have API to read/write files, make http requests, etc.

**Comment by rogsmith** [comment]
fyi, adding this in the mix.lock is what fixed my issues: "erlang_v8": {:git, "git://github.com/strange/erlang-v8.git", "1ca13321d5746f3ec20f0c0bfd2bcc8293db71da", []},

**Comment by le0pard** [comment]
Cool. Thanks!
