### ISSUE TITLE
Pending Release version - 0.3

### ISSUE THREAD

**Issue by devmarco** [le0pard/elixir_v8#8]
Pending merged PR's to be released.

- **Support the latest erlang_v8:** https://github.com/le0pard/elixir_v8/pull/6
- **Fix warning of mix: "please use parentheses to remove the ambiguity":** https://github.com/le0pard/elixir_v8/pull/4
- **Tiny fix of README:** https://github.com/le0pard/elixir_v8/pull/3

**Comment by le0pard** [comment]
@devmarco created new tag, but looks like I cannot publish new version from mix:

```
** (Mix) Stopping package build due to errors.
Dependencies excluded from the package (only Hex packages can be dependencies): erlang_v8
```

**Comment by le0pard** [comment]
@devmarco done
